# import pandas as pd
# import numpy as np
# from sklearn.ensemble import RandomForestRegressor
# srt = """JavaScript" NUMERIC NOT NULL DEFAULT 0, "Python" NUMERIC NOT NULL DEFAULT 0, "PHP" NUMERIC NOT NULL DEFAULT 0, "HTML" NUMERIC NOT NULL DEFAULT 0, "Yii" NUMERIC NOT NULL DEFAULT 0, "Linux" NUMERIC NOT NULL DEFAULT 0, "Flask" NUMERIC NOT NULL DEFAULT 0, "Redis" NUMERIC NOT NULL DEFAULT 0, "Docker" NUMERIC NOT NULL DEFAULT 0, "Django" NUMERIC NOT NULL DEFAULT 0, "Elasticsearch" NUMERIC NOT NULL DEFAULT 0, "Scrum" NUMERIC NOT NULL DEFAULT 0, "Pytest" NUMERIC NOT NULL DEFAULT 0, "TDD" NUMERIC NOT NULL DEFAULT 0, "Kibana" NUMERIC NOT NULL DEFAULT 0, "ELK" NUMERIC NOT NULL DEFAULT 0, "SOLID/KISS/DRY" NUMERIC NOT NULL DEFAULT 0, "SQL" NUMERIC NOT NULL DEFAULT 0, "API" NUMERIC NOT NULL DEFAULT 0, "OOP" NUMERIC NOT NULL DEFAULT 0, "CSS" NUMERIC NOT NULL DEFAULT 0, "GIT" NUMERIC NOT NULL DEFAULT 0, "Salary" INTEGER NOT NULL DEFAULT 0 );"""
# print(srt.replace("NUMERIC NOT NULL DEFAULT 0,", ";").replace(","," ").replace('"',""))


        